### ISSUE TITLE
Immersive Engineering License Violation

### ISSUE THREAD

**Issue by BluSunrize** [MechOrigin/NTC2#117]
Hi there!

I was made aware that you are currently distributing a binary of Immersive Engineering on this github page:

https://github.com/MechOrigin/NTC2/blob/master/mods/ImmersiveEngineering-1.16.5-5.1.0-148.jar

I am asking you very politely to take it down, because it is a direct violation of our license:

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/LICENSE#L15-L19

> #### What you *can not* do:
> - Redistribute this project (source or compiled) without explicit permission of the license holder, BluSunrize

I have **not** granted you permission for this redistribution and I am kindly requesting that you take it down, and instead redirect people to one of our endorsed points of distributions, [CurseForge](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering) or [Modrinth](https://modrinth.com/mod/immersiveengineering).

I am chosing to enforce this for the benefit of the users, because the sources we endorse are trusted to not pose a risk of malware - something I can not find guaranteed with your third party redistribution.
I really do not want to deal with the hassle of filing a takedown notice here, so I'd appreciate it if you saved me and yourselves the trouble =)

**Comment by MechOrigin** [comment]
This is a copy paste from a previous git but... I think it applied here.

I also rely on cursepoints for revenue. But I don't go after alpha builds on GitHub using my code or mods. Eventually this will get posted on curseforge but it makes it 10x more annoying for no reason, other than to not make a few bucks. Regardless.... I don't really care about the risk, or about licensing, Minecraft is a game for fun, you code for fun, Microsoft owns the source now so anybody who develops mods fall under their licensing because it's using their code, which last time I checked is completely open to distribute and whatnot, and you know what, even if im wrong... Take the stick out of your asses and get a life.

On another note, thanks for the heads up. I will choose to respect the wishes of the mod developers to not distribute their mods out of respect. I don't like rubbing anybody the wrong way and I prefer to have good relationships with everyone. So with that being said I will upload a manifest of the modpack pre alpha instead of the actual mods themselves.

I love you all, take care.

Closed.
