### ISSUE TITLE
Project EX Refined EMC Link has recipe, but does not work

### ISSUE THREAD

**Issue by Keurick** [MechOrigin/NTC2#37]
In their tooltip, a few Project EX items (Namely The Personal, Refined, and Compressed EMC Links)  have recipes enabled in the pack, but some have little to no functionality, resulting in players building the extremely expensive items for a useless outcome.

**Comment by RoyalBingBong** [comment]
ProjectEX seems to be abandoned. It hasn't been published since October 2021 and the latest code changes are for 1.18. There also seem to be issues between the mod author of ProjectE and ProjectEX, namely that ProjectE team has to deal with bug reports for ProjectEX (since the name is so close).

[Project Expansion](https://www.curseforge.com/minecraft/mc-mods/project-expansion) ([Repo](https://github.com/DonovanDMC/ProjectExpansion)) seems to be a decent alternative and is currently in active development.
The Transmutation Interface works with AE2 and provides all the items from your tablet to your AE2 system.

**Comment by MechOrigin** [comment]
Thanks @RoyalBingBong for the info.

Yes, 1.4.0 will be abandoning projectEX in favor to projectexpansion :)

Will close this.
