### ISSUE TITLE
AE2 interface set on block mode still push items in Assembler

### ISSUE THREAD

**Issue by Baptistemontan** [MechOrigin/NTC2#79]
I'm currently automating the creation of PCB and I wanted to use 1 assembler to make all components which require glue, but to avoid problems I set the interface to block mode, but it still push items when there are some in the assembler.
![image](https://user-images.githubusercontent.com/29284779/168314515-2b9957fd-1129-47db-948f-8821694c720c.png)
here its trying to push items for a transistor during the making of basic circuit board.

Edit: pack version: 1.4.4

Edit 2: After some testing it appears that this problem is common to all custom machines: 
![image](https://user-images.githubusercontent.com/29284779/168320132-3c04f8ee-662b-4668-806b-a2732b8f5fee.png)
interface is on block mode and its pushing the craft for a steel casing and a machine frame (it also seams that it can't push to the 2 last items placeholders). Also for a strange reason it don't wait to be hable to push every item in one go, if it can place one item it will push it, not waiting to have room for the other items of the craft.

**Comment by i2smrt4u** [comment]
I am having this same problem with more than just CustomMachines such as the Assembler. Blocking mode also does not work on my Induction Furnace, causing the crafting of the various Hardened Glasses to be challenging.

**Comment by tornewuff** [comment]
AE2's blocking mode does nothing for most machines, unfortunately. When blocking mode is enabled on an interface, before inserting items, it checks if it's possible to *remove* any items. If it would be possible to remove something, then it waits until there's nothing to remove before continuing to insert items. Almost all modded machines are set up so that their input slots cannot have items pulled out via inventory access, so AE2 will decide that it's okay to insert more items right away.

This is totally different to Refined Storage's blocking mode, which waits *until the output of the autocraft has been received* before it continues. That method works correctly for virtually all cases, but can be quite slow for multi-step crafting processes (when a machine is outputting directly to another machine before the product returns to the network).

I think AE2's blocking is just a design from much older days of modded Minecraft, where machines were more likely to have preconfigured per-side inventories like vanilla furnaces. If your machine outputs only from the bottom then it's not a problem if the input inventory allows two-way access, because any automation the player builds will be extracting from the bottom and inserting into some other side, and thus the output handling can never accidentally remove items from the input. But, almost all modern mods either allow both input and output from any side such that inserting always accesses the input inventory and extracting always accesses the output inventory, or have configurable I/O that usually includes the possibility of making a side both an input and output.

So, yeah, for predefined mod machines like the induction furnace this cannot be fixed by the pack author; that's just how the mod works. If the custom machine mod allows you to create a sided machine with two-way access to the input slots, then changing the pack to do that would enable the use of AE2 blocking mode on the custom machines, but would break any existing automation that was using other sides. I'm not sure if the mod supports that or not, in any case.
