### ISSUE TITLE
Electrum can no longer be crafted from Electrum Essence

### ISSUE THREAD

**Issue by ChromaLux** [MechOrigin/NTC2#88]
Electrum ingots no longer have a crafting recipe using Electrum Essence.

**Comment by zapl** [comment]
It's not just electrum. Essences that have no use:

* Air
* **Silicon**
* **Aluminum**
* **Saltpeter** (potassium nitrate)
* _Apatite_
* _Zinc_
* _Brass_
* **Silver**
* **Lead**
* **Nickel**
* **Constantan**
* **Electrum**
* **Invar**
* Mithril (seems unavailble)
* _Tungesten_
* _Titanium_
* **Uranium**
* Chrome (seems unavailable)
* _Ruby_
* _Sapphire_
* **Signalum**
* **Lumium**
* _Platium_
* _Iridium_
* **Enderium**
* Piglin Brute

Some of them are probably useless on purpose because the resource isn't meant to exist in the pack but there are several important ingots that stopped working. I guess that's because they try to craft the wrong type of ingot or something like that?
Most of them are Emendatus Enigmatica Ingots, but some from that mod are fine like copper, tin and osmium.

**Comment by zapl** [comment]
The fix to this is to revert the broken [config/cucumber-tags.json](https://github.com/MechOrigin/NTC2/commit/3715f1aaf04c0257ff6677c854fdf48f86a8f9f9#diff-8a3dd1f1ec70516d4e4caf7012ed257c38eb0278a2f136cbfff4a2d3ccd13f85)
 
it was replaced with an invalid binary file
